plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mk15.portinspector'
    compileSdk 34
    ndkVersion '28.2.13676358'

    defaultConfig {
        applicationId 'com.mk15.portinspector'
        minSdk 23
        targetSdk 28
        versionCode 40
        versionName '1.4.0'

        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    externalNativeBuild {
        ndkBuild {
            path file('src/main/jni/Android.mk')
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
